/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProduitRouteImport } from './routes/produit'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AuthenticatedEntrepriseCandidaturesRouteImport } from './routes/_authenticated/entreprise.candidatures'
import { Route as AuthenticatedEntrepriseDashboardRouteImport } from './routes/_authenticated/entreprise.dashboard'
import { Route as AuthenticatedEntrepriseEntretiensRouteImport } from './routes/_authenticated/entreprise.entretiens'
import { Route as AuthenticatedEntrepriseHistoriqueRouteImport } from './routes/_authenticated/entreprise.historique'
import { Route as AuthenticatedEntrepriseMessagerieRouteImport } from './routes/_authenticated/entreprise.messagerie'
import { Route as AuthenticatedEntreprisePaiementsRouteImport } from './routes/_authenticated/entreprise.paiements'
import { Route as AuthenticatedEntrepriseParametresRouteImport } from './routes/_authenticated/entreprise.parametres'
import { Route as AuthenticatedEntrepriseRecommandationsRouteImport } from './routes/_authenticated/entreprise.recommandations'
import { Route as AuthenticatedEntrepriseShortlistRouteImport } from './routes/_authenticated/entreprise.shortlist'
import { Route as AuthenticatedFreelanceCandidaturesRouteImport } from './routes/_authenticated/freelance.candidatures'
import { Route as AuthenticatedFreelanceDashboardRouteImport } from './routes/_authenticated/freelance.dashboard'
import { Route as AuthenticatedFreelanceMessagerieRouteImport } from './routes/_authenticated/freelance.messagerie'
import { Route as AuthenticatedFreelanceParametresRouteImport } from './routes/_authenticated/freelance.parametres'
import { Route as AuthenticatedFreelanceProfilRouteImport } from './routes/_authenticated/freelance.profil'
import { Route as AuthenticatedFreelanceRevenusRouteImport } from './routes/_authenticated/freelance.revenus'
import { Route as AuthenticatedFreelanceSuiviRouteImport } from './routes/_authenticated/freelance.suivi'
import { Route as AuthenticatedEntrepriseFreelancesIndexRouteImport } from './routes/_authenticated/entreprise.freelances.index'
import { Route as AuthenticatedEntrepriseFreelancesFreelanceIdRouteImport } from './routes/_authenticated/entreprise.freelances.$freelanceId'
import { Route as AuthenticatedEntrepriseMissionsIndexRouteImport } from './routes/_authenticated/entreprise.missions.index'
import { Route as AuthenticatedEntrepriseMissionsMissionIdRouteImport } from './routes/_authenticated/entreprise.missions.$missionId'
import { Route as AuthenticatedFreelanceMissionsIndexRouteImport } from './routes/_authenticated/freelance.missions.index'
import { Route as AuthenticatedFreelanceMissionsMissionIdRouteImport } from './routes/_authenticated/freelance.missions.$missionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitRoute = ProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEntrepriseCandidaturesRoute =
  AuthenticatedEntrepriseCandidaturesRouteImport.update({
    id: '/entreprise/candidatures',
    path: '/entreprise/candidatures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseDashboardRoute =
  AuthenticatedEntrepriseDashboardRouteImport.update({
    id: '/entreprise/dashboard',
    path: '/entreprise/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseEntretiensRoute =
  AuthenticatedEntrepriseEntretiensRouteImport.update({
    id: '/entreprise/entretiens',
    path: '/entreprise/entretiens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseHistoriqueRoute =
  AuthenticatedEntrepriseHistoriqueRouteImport.update({
    id: '/entreprise/historique',
    path: '/entreprise/historique',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseMessagerieRoute =
  AuthenticatedEntrepriseMessagerieRouteImport.update({
    id: '/entreprise/messagerie',
    path: '/entreprise/messagerie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntreprisePaiementsRoute =
  AuthenticatedEntreprisePaiementsRouteImport.update({
    id: '/entreprise/paiements',
    path: '/entreprise/paiements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseParametresRoute =
  AuthenticatedEntrepriseParametresRouteImport.update({
    id: '/entreprise/parametres',
    path: '/entreprise/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseRecommandationsRoute =
  AuthenticatedEntrepriseRecommandationsRouteImport.update({
    id: '/entreprise/recommandations',
    path: '/entreprise/recommandations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseShortlistRoute =
  AuthenticatedEntrepriseShortlistRouteImport.update({
    id: '/entreprise/shortlist',
    path: '/entreprise/shortlist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceCandidaturesRoute =
  AuthenticatedFreelanceCandidaturesRouteImport.update({
    id: '/freelance/candidatures',
    path: '/freelance/candidatures',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceDashboardRoute =
  AuthenticatedFreelanceDashboardRouteImport.update({
    id: '/freelance/dashboard',
    path: '/freelance/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceMessagerieRoute =
  AuthenticatedFreelanceMessagerieRouteImport.update({
    id: '/freelance/messagerie',
    path: '/freelance/messagerie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceParametresRoute =
  AuthenticatedFreelanceParametresRouteImport.update({
    id: '/freelance/parametres',
    path: '/freelance/parametres',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceProfilRoute =
  AuthenticatedFreelanceProfilRouteImport.update({
    id: '/freelance/profil',
    path: '/freelance/profil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceRevenusRoute =
  AuthenticatedFreelanceRevenusRouteImport.update({
    id: '/freelance/revenus',
    path: '/freelance/revenus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceSuiviRoute =
  AuthenticatedFreelanceSuiviRouteImport.update({
    id: '/freelance/suivi',
    path: '/freelance/suivi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseFreelancesIndexRoute =
  AuthenticatedEntrepriseFreelancesIndexRouteImport.update({
    id: '/entreprise/freelances/',
    path: '/entreprise/freelances/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseFreelancesFreelanceIdRoute =
  AuthenticatedEntrepriseFreelancesFreelanceIdRouteImport.update({
    id: '/entreprise/freelances/$freelanceId',
    path: '/entreprise/freelances/$freelanceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseMissionsIndexRoute =
  AuthenticatedEntrepriseMissionsIndexRouteImport.update({
    id: '/entreprise/missions/',
    path: '/entreprise/missions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntrepriseMissionsMissionIdRoute =
  AuthenticatedEntrepriseMissionsMissionIdRouteImport.update({
    id: '/entreprise/missions/$missionId',
    path: '/entreprise/missions/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceMissionsIndexRoute =
  AuthenticatedFreelanceMissionsIndexRouteImport.update({
    id: '/freelance/missions/',
    path: '/freelance/missions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFreelanceMissionsMissionIdRoute =
  AuthenticatedFreelanceMissionsMissionIdRouteImport.update({
    id: '/freelance/missions/$missionId',
    path: '/freelance/missions/$missionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produit': typeof ProduitRoute
  '/tarifs': typeof TarifsRoute
  '/entreprise/candidatures': typeof AuthenticatedEntrepriseCandidaturesRoute
  '/entreprise/dashboard': typeof AuthenticatedEntrepriseDashboardRoute
  '/entreprise/entretiens': typeof AuthenticatedEntrepriseEntretiensRoute
  '/entreprise/historique': typeof AuthenticatedEntrepriseHistoriqueRoute
  '/entreprise/messagerie': typeof AuthenticatedEntrepriseMessagerieRoute
  '/entreprise/paiements': typeof AuthenticatedEntreprisePaiementsRoute
  '/entreprise/parametres': typeof AuthenticatedEntrepriseParametresRoute
  '/entreprise/recommandations': typeof AuthenticatedEntrepriseRecommandationsRoute
  '/entreprise/shortlist': typeof AuthenticatedEntrepriseShortlistRoute
  '/freelance/candidatures': typeof AuthenticatedFreelanceCandidaturesRoute
  '/freelance/dashboard': typeof AuthenticatedFreelanceDashboardRoute
  '/freelance/messagerie': typeof AuthenticatedFreelanceMessagerieRoute
  '/freelance/parametres': typeof AuthenticatedFreelanceParametresRoute
  '/freelance/profil': typeof AuthenticatedFreelanceProfilRoute
  '/freelance/revenus': typeof AuthenticatedFreelanceRevenusRoute
  '/freelance/suivi': typeof AuthenticatedFreelanceSuiviRoute
  '/entreprise/freelances/$freelanceId': typeof AuthenticatedEntrepriseFreelancesFreelanceIdRoute
  '/entreprise/missions/$missionId': typeof AuthenticatedEntrepriseMissionsMissionIdRoute
  '/freelance/missions/$missionId': typeof AuthenticatedFreelanceMissionsMissionIdRoute
  '/entreprise/freelances/': typeof AuthenticatedEntrepriseFreelancesIndexRoute
  '/entreprise/missions/': typeof AuthenticatedEntrepriseMissionsIndexRoute
  '/freelance/missions/': typeof AuthenticatedFreelanceMissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produit': typeof ProduitRoute
  '/tarifs': typeof TarifsRoute
  '/entreprise/candidatures': typeof AuthenticatedEntrepriseCandidaturesRoute
  '/entreprise/dashboard': typeof AuthenticatedEntrepriseDashboardRoute
  '/entreprise/entretiens': typeof AuthenticatedEntrepriseEntretiensRoute
  '/entreprise/historique': typeof AuthenticatedEntrepriseHistoriqueRoute
  '/entreprise/messagerie': typeof AuthenticatedEntrepriseMessagerieRoute
  '/entreprise/paiements': typeof AuthenticatedEntreprisePaiementsRoute
  '/entreprise/parametres': typeof AuthenticatedEntrepriseParametresRoute
  '/entreprise/recommandations': typeof AuthenticatedEntrepriseRecommandationsRoute
  '/entreprise/shortlist': typeof AuthenticatedEntrepriseShortlistRoute
  '/freelance/candidatures': typeof AuthenticatedFreelanceCandidaturesRoute
  '/freelance/dashboard': typeof AuthenticatedFreelanceDashboardRoute
  '/freelance/messagerie': typeof AuthenticatedFreelanceMessagerieRoute
  '/freelance/parametres': typeof AuthenticatedFreelanceParametresRoute
  '/freelance/profil': typeof AuthenticatedFreelanceProfilRoute
  '/freelance/revenus': typeof AuthenticatedFreelanceRevenusRoute
  '/freelance/suivi': typeof AuthenticatedFreelanceSuiviRoute
  '/entreprise/freelances/$freelanceId': typeof AuthenticatedEntrepriseFreelancesFreelanceIdRoute
  '/entreprise/missions/$missionId': typeof AuthenticatedEntrepriseMissionsMissionIdRoute
  '/freelance/missions/$missionId': typeof AuthenticatedFreelanceMissionsMissionIdRoute
  '/entreprise/freelances': typeof AuthenticatedEntrepriseFreelancesIndexRoute
  '/entreprise/missions': typeof AuthenticatedEntrepriseMissionsIndexRoute
  '/freelance/missions': typeof AuthenticatedFreelanceMissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/produit': typeof ProduitRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/entreprise/candidatures': typeof AuthenticatedEntrepriseCandidaturesRoute
  '/_authenticated/entreprise/dashboard': typeof AuthenticatedEntrepriseDashboardRoute
  '/_authenticated/entreprise/entretiens': typeof AuthenticatedEntrepriseEntretiensRoute
  '/_authenticated/entreprise/historique': typeof AuthenticatedEntrepriseHistoriqueRoute
  '/_authenticated/entreprise/messagerie': typeof AuthenticatedEntrepriseMessagerieRoute
  '/_authenticated/entreprise/paiements': typeof AuthenticatedEntreprisePaiementsRoute
  '/_authenticated/entreprise/parametres': typeof AuthenticatedEntrepriseParametresRoute
  '/_authenticated/entreprise/recommandations': typeof AuthenticatedEntrepriseRecommandationsRoute
  '/_authenticated/entreprise/shortlist': typeof AuthenticatedEntrepriseShortlistRoute
  '/_authenticated/freelance/candidatures': typeof AuthenticatedFreelanceCandidaturesRoute
  '/_authenticated/freelance/dashboard': typeof AuthenticatedFreelanceDashboardRoute
  '/_authenticated/freelance/messagerie': typeof AuthenticatedFreelanceMessagerieRoute
  '/_authenticated/freelance/parametres': typeof AuthenticatedFreelanceParametresRoute
  '/_authenticated/freelance/profil': typeof AuthenticatedFreelanceProfilRoute
  '/_authenticated/freelance/revenus': typeof AuthenticatedFreelanceRevenusRoute
  '/_authenticated/freelance/suivi': typeof AuthenticatedFreelanceSuiviRoute
  '/_authenticated/entreprise/freelances/$freelanceId': typeof AuthenticatedEntrepriseFreelancesFreelanceIdRoute
  '/_authenticated/entreprise/missions/$missionId': typeof AuthenticatedEntrepriseMissionsMissionIdRoute
  '/_authenticated/freelance/missions/$missionId': typeof AuthenticatedFreelanceMissionsMissionIdRoute
  '/_authenticated/entreprise/freelances/': typeof AuthenticatedEntrepriseFreelancesIndexRoute
  '/_authenticated/entreprise/missions/': typeof AuthenticatedEntrepriseMissionsIndexRoute
  '/_authenticated/freelance/missions/': typeof AuthenticatedFreelanceMissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/produit'
    | '/tarifs'
    | '/entreprise/candidatures'
    | '/entreprise/dashboard'
    | '/entreprise/entretiens'
    | '/entreprise/historique'
    | '/entreprise/messagerie'
    | '/entreprise/paiements'
    | '/entreprise/parametres'
    | '/entreprise/recommandations'
    | '/entreprise/shortlist'
    | '/freelance/candidatures'
    | '/freelance/dashboard'
    | '/freelance/messagerie'
    | '/freelance/parametres'
    | '/freelance/profil'
    | '/freelance/revenus'
    | '/freelance/suivi'
    | '/entreprise/freelances/$freelanceId'
    | '/entreprise/missions/$missionId'
    | '/freelance/missions/$missionId'
    | '/entreprise/freelances/'
    | '/entreprise/missions/'
    | '/freelance/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/produit'
    | '/tarifs'
    | '/entreprise/candidatures'
    | '/entreprise/dashboard'
    | '/entreprise/entretiens'
    | '/entreprise/historique'
    | '/entreprise/messagerie'
    | '/entreprise/paiements'
    | '/entreprise/parametres'
    | '/entreprise/recommandations'
    | '/entreprise/shortlist'
    | '/freelance/candidatures'
    | '/freelance/dashboard'
    | '/freelance/messagerie'
    | '/freelance/parametres'
    | '/freelance/profil'
    | '/freelance/revenus'
    | '/freelance/suivi'
    | '/entreprise/freelances/$freelanceId'
    | '/entreprise/missions/$missionId'
    | '/freelance/missions/$missionId'
    | '/entreprise/freelances'
    | '/entreprise/missions'
    | '/freelance/missions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/produit'
    | '/tarifs'
    | '/_authenticated/entreprise/candidatures'
    | '/_authenticated/entreprise/dashboard'
    | '/_authenticated/entreprise/entretiens'
    | '/_authenticated/entreprise/historique'
    | '/_authenticated/entreprise/messagerie'
    | '/_authenticated/entreprise/paiements'
    | '/_authenticated/entreprise/parametres'
    | '/_authenticated/entreprise/recommandations'
    | '/_authenticated/entreprise/shortlist'
    | '/_authenticated/freelance/candidatures'
    | '/_authenticated/freelance/dashboard'
    | '/_authenticated/freelance/messagerie'
    | '/_authenticated/freelance/parametres'
    | '/_authenticated/freelance/profil'
    | '/_authenticated/freelance/revenus'
    | '/_authenticated/freelance/suivi'
    | '/_authenticated/entreprise/freelances/$freelanceId'
    | '/_authenticated/entreprise/missions/$missionId'
    | '/_authenticated/freelance/missions/$missionId'
    | '/_authenticated/entreprise/freelances/'
    | '/_authenticated/entreprise/missions/'
    | '/_authenticated/freelance/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProduitRoute: typeof ProduitRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit': {
      id: '/produit'
      path: '/produit'
      fullPath: '/produit'
      preLoaderRoute: typeof ProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/entreprise/candidatures': {
      id: '/_authenticated/entreprise/candidatures'
      path: '/entreprise/candidatures'
      fullPath: '/entreprise/candidatures'
      preLoaderRoute: typeof AuthenticatedEntrepriseCandidaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/dashboard': {
      id: '/_authenticated/entreprise/dashboard'
      path: '/entreprise/dashboard'
      fullPath: '/entreprise/dashboard'
      preLoaderRoute: typeof AuthenticatedEntrepriseDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/entretiens': {
      id: '/_authenticated/entreprise/entretiens'
      path: '/entreprise/entretiens'
      fullPath: '/entreprise/entretiens'
      preLoaderRoute: typeof AuthenticatedEntrepriseEntretiensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/historique': {
      id: '/_authenticated/entreprise/historique'
      path: '/entreprise/historique'
      fullPath: '/entreprise/historique'
      preLoaderRoute: typeof AuthenticatedEntrepriseHistoriqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/messagerie': {
      id: '/_authenticated/entreprise/messagerie'
      path: '/entreprise/messagerie'
      fullPath: '/entreprise/messagerie'
      preLoaderRoute: typeof AuthenticatedEntrepriseMessagerieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/paiements': {
      id: '/_authenticated/entreprise/paiements'
      path: '/entreprise/paiements'
      fullPath: '/entreprise/paiements'
      preLoaderRoute: typeof AuthenticatedEntreprisePaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/parametres': {
      id: '/_authenticated/entreprise/parametres'
      path: '/entreprise/parametres'
      fullPath: '/entreprise/parametres'
      preLoaderRoute: typeof AuthenticatedEntrepriseParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/recommandations': {
      id: '/_authenticated/entreprise/recommandations'
      path: '/entreprise/recommandations'
      fullPath: '/entreprise/recommandations'
      preLoaderRoute: typeof AuthenticatedEntrepriseRecommandationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/shortlist': {
      id: '/_authenticated/entreprise/shortlist'
      path: '/entreprise/shortlist'
      fullPath: '/entreprise/shortlist'
      preLoaderRoute: typeof AuthenticatedEntrepriseShortlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/candidatures': {
      id: '/_authenticated/freelance/candidatures'
      path: '/freelance/candidatures'
      fullPath: '/freelance/candidatures'
      preLoaderRoute: typeof AuthenticatedFreelanceCandidaturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/dashboard': {
      id: '/_authenticated/freelance/dashboard'
      path: '/freelance/dashboard'
      fullPath: '/freelance/dashboard'
      preLoaderRoute: typeof AuthenticatedFreelanceDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/messagerie': {
      id: '/_authenticated/freelance/messagerie'
      path: '/freelance/messagerie'
      fullPath: '/freelance/messagerie'
      preLoaderRoute: typeof AuthenticatedFreelanceMessagerieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/parametres': {
      id: '/_authenticated/freelance/parametres'
      path: '/freelance/parametres'
      fullPath: '/freelance/parametres'
      preLoaderRoute: typeof AuthenticatedFreelanceParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/profil': {
      id: '/_authenticated/freelance/profil'
      path: '/freelance/profil'
      fullPath: '/freelance/profil'
      preLoaderRoute: typeof AuthenticatedFreelanceProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/revenus': {
      id: '/_authenticated/freelance/revenus'
      path: '/freelance/revenus'
      fullPath: '/freelance/revenus'
      preLoaderRoute: typeof AuthenticatedFreelanceRevenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/suivi': {
      id: '/_authenticated/freelance/suivi'
      path: '/freelance/suivi'
      fullPath: '/freelance/suivi'
      preLoaderRoute: typeof AuthenticatedFreelanceSuiviRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/freelances/': {
      id: '/_authenticated/entreprise/freelances/'
      path: '/entreprise/freelances'
      fullPath: '/entreprise/freelances/'
      preLoaderRoute: typeof AuthenticatedEntrepriseFreelancesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/freelances/$freelanceId': {
      id: '/_authenticated/entreprise/freelances/$freelanceId'
      path: '/entreprise/freelances/$freelanceId'
      fullPath: '/entreprise/freelances/$freelanceId'
      preLoaderRoute: typeof AuthenticatedEntrepriseFreelancesFreelanceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/missions/': {
      id: '/_authenticated/entreprise/missions/'
      path: '/entreprise/missions'
      fullPath: '/entreprise/missions/'
      preLoaderRoute: typeof AuthenticatedEntrepriseMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entreprise/missions/$missionId': {
      id: '/_authenticated/entreprise/missions/$missionId'
      path: '/entreprise/missions/$missionId'
      fullPath: '/entreprise/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedEntrepriseMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/missions/': {
      id: '/_authenticated/freelance/missions/'
      path: '/freelance/missions'
      fullPath: '/freelance/missions/'
      preLoaderRoute: typeof AuthenticatedFreelanceMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/freelance/missions/$missionId': {
      id: '/_authenticated/freelance/missions/$missionId'
      path: '/freelance/missions/$missionId'
      fullPath: '/freelance/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedFreelanceMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEntrepriseCandidaturesRoute: typeof AuthenticatedEntrepriseCandidaturesRoute
  AuthenticatedEntrepriseDashboardRoute: typeof AuthenticatedEntrepriseDashboardRoute
  AuthenticatedEntrepriseEntretiensRoute: typeof AuthenticatedEntrepriseEntretiensRoute
  AuthenticatedEntrepriseHistoriqueRoute: typeof AuthenticatedEntrepriseHistoriqueRoute
  AuthenticatedEntrepriseMessagerieRoute: typeof AuthenticatedEntrepriseMessagerieRoute
  AuthenticatedEntreprisePaiementsRoute: typeof AuthenticatedEntreprisePaiementsRoute
  AuthenticatedEntrepriseParametresRoute: typeof AuthenticatedEntrepriseParametresRoute
  AuthenticatedEntrepriseRecommandationsRoute: typeof AuthenticatedEntrepriseRecommandationsRoute
  AuthenticatedEntrepriseShortlistRoute: typeof AuthenticatedEntrepriseShortlistRoute
  AuthenticatedFreelanceCandidaturesRoute: typeof AuthenticatedFreelanceCandidaturesRoute
  AuthenticatedFreelanceDashboardRoute: typeof AuthenticatedFreelanceDashboardRoute
  AuthenticatedFreelanceMessagerieRoute: typeof AuthenticatedFreelanceMessagerieRoute
  AuthenticatedFreelanceParametresRoute: typeof AuthenticatedFreelanceParametresRoute
  AuthenticatedFreelanceProfilRoute: typeof AuthenticatedFreelanceProfilRoute
  AuthenticatedFreelanceRevenusRoute: typeof AuthenticatedFreelanceRevenusRoute
  AuthenticatedFreelanceSuiviRoute: typeof AuthenticatedFreelanceSuiviRoute
  AuthenticatedEntrepriseFreelancesFreelanceIdRoute: typeof AuthenticatedEntrepriseFreelancesFreelanceIdRoute
  AuthenticatedEntrepriseMissionsMissionIdRoute: typeof AuthenticatedEntrepriseMissionsMissionIdRoute
  AuthenticatedFreelanceMissionsMissionIdRoute: typeof AuthenticatedFreelanceMissionsMissionIdRoute
  AuthenticatedEntrepriseFreelancesIndexRoute: typeof AuthenticatedEntrepriseFreelancesIndexRoute
  AuthenticatedEntrepriseMissionsIndexRoute: typeof AuthenticatedEntrepriseMissionsIndexRoute
  AuthenticatedFreelanceMissionsIndexRoute: typeof AuthenticatedFreelanceMissionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEntrepriseCandidaturesRoute:
    AuthenticatedEntrepriseCandidaturesRoute,
  AuthenticatedEntrepriseDashboardRoute: AuthenticatedEntrepriseDashboardRoute,
  AuthenticatedEntrepriseEntretiensRoute:
    AuthenticatedEntrepriseEntretiensRoute,
  AuthenticatedEntrepriseHistoriqueRoute:
    AuthenticatedEntrepriseHistoriqueRoute,
  AuthenticatedEntrepriseMessagerieRoute:
    AuthenticatedEntrepriseMessagerieRoute,
  AuthenticatedEntreprisePaiementsRoute: AuthenticatedEntreprisePaiementsRoute,
  AuthenticatedEntrepriseParametresRoute:
    AuthenticatedEntrepriseParametresRoute,
  AuthenticatedEntrepriseRecommandationsRoute:
    AuthenticatedEntrepriseRecommandationsRoute,
  AuthenticatedEntrepriseShortlistRoute: AuthenticatedEntrepriseShortlistRoute,
  AuthenticatedFreelanceCandidaturesRoute:
    AuthenticatedFreelanceCandidaturesRoute,
  AuthenticatedFreelanceDashboardRoute: AuthenticatedFreelanceDashboardRoute,
  AuthenticatedFreelanceMessagerieRoute: AuthenticatedFreelanceMessagerieRoute,
  AuthenticatedFreelanceParametresRoute: AuthenticatedFreelanceParametresRoute,
  AuthenticatedFreelanceProfilRoute: AuthenticatedFreelanceProfilRoute,
  AuthenticatedFreelanceRevenusRoute: AuthenticatedFreelanceRevenusRoute,
  AuthenticatedFreelanceSuiviRoute: AuthenticatedFreelanceSuiviRoute,
  AuthenticatedEntrepriseFreelancesFreelanceIdRoute:
    AuthenticatedEntrepriseFreelancesFreelanceIdRoute,
  AuthenticatedEntrepriseMissionsMissionIdRoute:
    AuthenticatedEntrepriseMissionsMissionIdRoute,
  AuthenticatedFreelanceMissionsMissionIdRoute:
    AuthenticatedFreelanceMissionsMissionIdRoute,
  AuthenticatedEntrepriseFreelancesIndexRoute:
    AuthenticatedEntrepriseFreelancesIndexRoute,
  AuthenticatedEntrepriseMissionsIndexRoute:
    AuthenticatedEntrepriseMissionsIndexRoute,
  AuthenticatedFreelanceMissionsIndexRoute:
    AuthenticatedFreelanceMissionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProduitRoute: ProduitRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
