/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProduitRouteImport } from './routes/produit'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as DashboardEntrepriseRouteImport } from './routes/dashboard.entreprise'
import { Route as DashboardFreelanceRouteImport } from './routes/dashboard.freelance'
import { Route as FreelancesIndexRouteImport } from './routes/freelances.index'
import { Route as FreelancesFreelanceIdRouteImport } from './routes/freelances.$freelanceId'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as MissionsMissionIdRouteImport } from './routes/missions.$missionId'
import { Route as OnboardingEntrepriseRouteImport } from './routes/onboarding.entreprise'
import { Route as OnboardingFreelanceRouteImport } from './routes/onboarding.freelance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitRoute = ProduitRouteImport.update({
  id: '/produit',
  path: '/produit',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEntrepriseRoute = DashboardEntrepriseRouteImport.update({
  id: '/dashboard/entreprise',
  path: '/dashboard/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFreelanceRoute = DashboardFreelanceRouteImport.update({
  id: '/dashboard/freelance',
  path: '/dashboard/freelance',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancesIndexRoute = FreelancesIndexRouteImport.update({
  id: '/freelances/',
  path: '/freelances/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancesFreelanceIdRoute = FreelancesFreelanceIdRouteImport.update({
  id: '/freelances/$freelanceId',
  path: '/freelances/$freelanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/missions/',
  path: '/missions/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsMissionIdRoute = MissionsMissionIdRouteImport.update({
  id: '/missions/$missionId',
  path: '/missions/$missionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEntrepriseRoute = OnboardingEntrepriseRouteImport.update({
  id: '/onboarding/entreprise',
  path: '/onboarding/entreprise',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFreelanceRoute = OnboardingFreelanceRouteImport.update({
  id: '/onboarding/freelance',
  path: '/onboarding/freelance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produit': typeof ProduitRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard/entreprise': typeof DashboardEntrepriseRoute
  '/dashboard/freelance': typeof DashboardFreelanceRoute
  '/freelances/$freelanceId': typeof FreelancesFreelanceIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/onboarding/entreprise': typeof OnboardingEntrepriseRoute
  '/onboarding/freelance': typeof OnboardingFreelanceRoute
  '/freelances/': typeof FreelancesIndexRoute
  '/missions/': typeof MissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produit': typeof ProduitRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard/entreprise': typeof DashboardEntrepriseRoute
  '/dashboard/freelance': typeof DashboardFreelanceRoute
  '/freelances/$freelanceId': typeof FreelancesFreelanceIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/onboarding/entreprise': typeof OnboardingEntrepriseRoute
  '/onboarding/freelance': typeof OnboardingFreelanceRoute
  '/freelances': typeof FreelancesIndexRoute
  '/missions': typeof MissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/produit': typeof ProduitRoute
  '/tarifs': typeof TarifsRoute
  '/dashboard/entreprise': typeof DashboardEntrepriseRoute
  '/dashboard/freelance': typeof DashboardFreelanceRoute
  '/freelances/$freelanceId': typeof FreelancesFreelanceIdRoute
  '/missions/$missionId': typeof MissionsMissionIdRoute
  '/onboarding/entreprise': typeof OnboardingEntrepriseRoute
  '/onboarding/freelance': typeof OnboardingFreelanceRoute
  '/freelances/': typeof FreelancesIndexRoute
  '/missions/': typeof MissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/produit'
    | '/tarifs'
    | '/dashboard/entreprise'
    | '/dashboard/freelance'
    | '/freelances/$freelanceId'
    | '/missions/$missionId'
    | '/onboarding/entreprise'
    | '/onboarding/freelance'
    | '/freelances/'
    | '/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/produit'
    | '/tarifs'
    | '/dashboard/entreprise'
    | '/dashboard/freelance'
    | '/freelances/$freelanceId'
    | '/missions/$missionId'
    | '/onboarding/entreprise'
    | '/onboarding/freelance'
    | '/freelances'
    | '/missions'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/produit'
    | '/tarifs'
    | '/dashboard/entreprise'
    | '/dashboard/freelance'
    | '/freelances/$freelanceId'
    | '/missions/$missionId'
    | '/onboarding/entreprise'
    | '/onboarding/freelance'
    | '/freelances/'
    | '/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ProduitRoute: typeof ProduitRoute
  TarifsRoute: typeof TarifsRoute
  DashboardEntrepriseRoute: typeof DashboardEntrepriseRoute
  DashboardFreelanceRoute: typeof DashboardFreelanceRoute
  FreelancesFreelanceIdRoute: typeof FreelancesFreelanceIdRoute
  MissionsMissionIdRoute: typeof MissionsMissionIdRoute
  OnboardingEntrepriseRoute: typeof OnboardingEntrepriseRoute
  OnboardingFreelanceRoute: typeof OnboardingFreelanceRoute
  FreelancesIndexRoute: typeof FreelancesIndexRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit': {
      id: '/produit'
      path: '/produit'
      fullPath: '/produit'
      preLoaderRoute: typeof ProduitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/entreprise': {
      id: '/dashboard/entreprise'
      path: '/dashboard/entreprise'
      fullPath: '/dashboard/entreprise'
      preLoaderRoute: typeof DashboardEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/freelance': {
      id: '/dashboard/freelance'
      path: '/dashboard/freelance'
      fullPath: '/dashboard/freelance'
      preLoaderRoute: typeof DashboardFreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelances/': {
      id: '/freelances/'
      path: '/freelances'
      fullPath: '/freelances/'
      preLoaderRoute: typeof FreelancesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelances/$freelanceId': {
      id: '/freelances/$freelanceId'
      path: '/freelances/$freelanceId'
      fullPath: '/freelances/$freelanceId'
      preLoaderRoute: typeof FreelancesFreelanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$missionId': {
      id: '/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof MissionsMissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/entreprise': {
      id: '/onboarding/entreprise'
      path: '/onboarding/entreprise'
      fullPath: '/onboarding/entreprise'
      preLoaderRoute: typeof OnboardingEntrepriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/freelance': {
      id: '/onboarding/freelance'
      path: '/onboarding/freelance'
      fullPath: '/onboarding/freelance'
      preLoaderRoute: typeof OnboardingFreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ProduitRoute: ProduitRoute,
  TarifsRoute: TarifsRoute,
  DashboardEntrepriseRoute: DashboardEntrepriseRoute,
  DashboardFreelanceRoute: DashboardFreelanceRoute,
  FreelancesFreelanceIdRoute: FreelancesFreelanceIdRoute,
  MissionsMissionIdRoute: MissionsMissionIdRoute,
  OnboardingEntrepriseRoute: OnboardingEntrepriseRoute,
  OnboardingFreelanceRoute: OnboardingFreelanceRoute,
  FreelancesIndexRoute: FreelancesIndexRoute,
  MissionsIndexRoute: MissionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
